version: '3.7'

services:

  nginx:
    image: nginx:mainline
    container_name: satis-repository
    volumes:
    - ./output:/usr/share/nginx/html
    expose:
    - 8000
    ports:
    - 8000:80
    cap_drop:
    - ALL
    cap_add:
    - CHOWN
    - SETUID
    - SETGID
    - NET_BIND_SERVICE
    healthcheck:
      test: nc -z localhost 8000
      interval: 5s

  satis:
    image: composer/satis:latest
    container_name: satis-bin
    init: true
    user: ${UID}:${GID}
    command:
    - 'true'
    volumes:
    - .:/build
    tmpfs:
    - /tmp
    - /composer
    cap_drop:
    - ALL
    cap_add:
    - SETUID
    - SETGID
    - DAC_OVERRIDE

  composer:
    image: composer:1
    container_name: satis-composer
    init: true
    user: ${UID}:${GID}
    command:
    - 'true'
    volumes:
    - .:/app
    tmpfs:
    - /tmp
    cap_drop:
    - ALL
    cap_add:
    - SETUID
    - SETGID
    - DAC_OVERRIDE
